import { useQuery } from "@tanstack/react-query";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, Legend, LineChart, Line } from "recharts";
import api from "../lib/api";
import { formatINR } from "../lib/utils";
import type { HealthScore, Anomaly, SpendingTrend } from "../types";
import { HeartPulse, ShieldAlert, Wallet, PiggyBank, Sparkles, Download, Calculator } from "lucide-react";

const PIE_COLORS=["#3b82f6","#10b981","#f59e0b","#ef4444","#8b5cf6","#06b6d4","#f97316"];

export default function Analytics(){
 const {data:health}=useQuery<HealthScore>({queryKey:["health-score"],queryFn:()=>api.get("/analytics/health-score").then(r=>r.data)});
 const {data:anomalies=[]}=useQuery<Anomaly[]>({queryKey:["anomalies"],queryFn:()=>api.get("/analytics/anomalies?days=90").then(r=>r.data)});
 const {data:trends=[]}=useQuery<SpendingTrend[]>({queryKey:["spending-trends"],queryFn:()=>api.get("/analytics/spending-trends?months=6").then(r=>r.data)});
 const {data:net}=useQuery<any>({queryKey:["net-worth"],queryFn:()=>api.get("/analytics/net-worth").then(r=>r.data)});
 const {data:emergency}=useQuery<any>({queryKey:["emergency-fund"],queryFn:()=>api.get("/analytics/emergency-fund").then(r=>r.data)});
 const {data:recommendations=[]}=useQuery<any[]>({queryKey:["budget-recommendations"],queryFn:()=>api.get("/analytics/budget-recommendations").then(r=>r.data)});
 const {data:report}=useQuery<any>({queryKey:["monthly-report"],queryFn:()=>api.get("/analytics/monthly-report").then(r=>r.data)});
 const {data:forecast}=useQuery<any>({queryKey:["cashflow"],queryFn:()=>api.get("/analytics/cashflow?days=30").then(r=>r.data)});
 const cats:Record<string,number>={}; trends.forEach(t=>cats[t.category_name]=(cats[t.category_name]||0)+Number(t.total_spent));
 const pieData=Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,7).map(([name,value])=>({name,value}));
 const monthTotals:Record<string,number>={}; trends.forEach(t=>monthTotals[t.month]=(monthTotals[t.month]||0)+Number(t.total_spent));
 const barData=Object.entries(monthTotals).sort().map(([month,total])=>({month,total}));
 const gradeColor:Record<string,string>={A:"text-emerald-600",B:"text-blue-600",C:"text-amber-600",D:"text-orange-600",F:"text-red-600"};
 const downloadReport=()=>{if(!report)return;const text=`FinWise Monthly Report\n${report.month}\nIncome: INR ${report.income}\nExpenses: INR ${report.expenses}\nSavings: INR ${report.savings}\nSavings rate: ${report.savings_rate}%\nExpense change: ${report.expense_change_pct}%`;const blob=new Blob([text],{type:"text/plain"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`finwise-report-${report.month}.txt`;a.click();URL.revokeObjectURL(a.href)};
 return <div className="space-y-6 page-shell">
  <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-4"><div><p className="text-sm font-semibold text-blue-600">Financial intelligence</p><h1 className="text-3xl font-black text-slate-900">Analytics & Insights</h1><p className="text-sm text-slate-500 mt-1">Understand, predict and improve your financial behavior.</p></div><button onClick={downloadReport} className="btn-secondary flex items-center gap-2"><Download size={16}/> Export monthly report</button></div>
  <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">
   <div className="card"><div className="flex items-center gap-3"><Wallet className="text-blue-600"/><div><p className="text-xs text-slate-400">Net worth</p><p className="text-2xl font-black">{formatINR(net?.net_worth||0)}</p></div></div><p className="text-xs text-slate-400 mt-3">Assets {formatINR(net?.assets||0)} · Liabilities {formatINR(net?.liabilities||0)}</p></div>
   <div className="card"><div className="flex items-center gap-3"><HeartPulse className="text-emerald-600"/><div><p className="text-xs text-slate-400">Health score</p><p className={`text-2xl font-black ${gradeColor[health?.grade||"F"]}`}>{health?.total_score?.toFixed(0)??"—"}/100</p></div></div><p className="text-xs text-slate-400 mt-3">Grade {health?.grade||"—"}</p></div>
   <div className="card"><div className="flex items-center gap-3"><ShieldAlert className="text-amber-600"/><div><p className="text-xs text-slate-400">Anomalies</p><p className="text-2xl font-black">{anomalies.length}</p></div></div><p className="text-xs text-slate-400 mt-3">Last 90 days · review flags</p></div>
   <div className="card"><div className="flex items-center gap-3"><PiggyBank className="text-violet-600"/><div><p className="text-xs text-slate-400">Emergency cover</p><p className="text-2xl font-black">{emergency?.months_covered?.toFixed(1)??"0.0"} mo</p></div></div><p className="text-xs text-slate-400 mt-3">3–6 months is a common planning range</p></div>
  </div>
  <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
   <div className="card"><h2 className="font-bold text-slate-800 mb-4">Financial Health Score</h2>{health?.factors.map(f=><div key={f.name} className="mb-4"><div className="flex justify-between text-sm"><span>{f.name}</span><span>{f.score}/{f.max_score}</span></div><div className="h-2 bg-slate-100 rounded-full mt-1 overflow-hidden"><div className="h-full bg-blue-500 rounded-full" style={{width:`${f.score/f.max_score*100}%`}}/></div><p className="text-xs text-slate-400 mt-1">{f.description}</p>{f.tip&&<p className="text-xs text-amber-600 mt-1">{f.tip}</p>}</div>)}<p className="text-[11px] text-slate-400 border-t pt-3">{health?.disclaimer}</p></div>
   <div className="card"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-800">Cash-flow forecast</h2><p className="text-xs text-slate-400">Next 30 days</p></div><Sparkles size={18} className="text-blue-600"/></div><ResponsiveContainer width="100%" height={260}><LineChart data={(forecast?.forecast||[]).slice(0,30)}><CartesianGrid strokeDasharray="3 3" stroke="#eef2f7"/><XAxis dataKey="date" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip/><Line type="monotone" dataKey="projected_balance" stroke="#2563eb" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer><p className="text-xs text-slate-400">Forecasts are estimates based on recent cash-flow patterns.</p></div>
  </div>
  <div className="grid grid-cols-1 lg:grid-cols-2 gap-5"><div className="card"><h2 className="font-bold text-slate-800 mb-4">Monthly spending</h2><ResponsiveContainer width="100%" height={230}><BarChart data={barData}><CartesianGrid strokeDasharray="3 3" stroke="#eef2f7"/><XAxis dataKey="month" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip formatter={(v:any)=>formatINR(Number(v))}/><Bar dataKey="total" fill="#3b82f6" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div><div className="card"><h2 className="font-bold text-slate-800 mb-4">Spending by category</h2><ResponsiveContainer width="100%" height={230}><PieChart><Pie data={pieData} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={78}>{pieData.map((_,i)=><Cell key={i} fill={PIE_COLORS[i%PIE_COLORS.length]}/>)}</Pie><Legend iconSize={9} wrapperStyle={{fontSize:11}}/><Tooltip formatter={(v:any)=>formatINR(Number(v))}/></PieChart></ResponsiveContainer></div></div>
  <div className="card"><div className="flex items-center gap-2 mb-4"><Calculator size={18} className="text-blue-600"/><div><h2 className="font-bold text-slate-800">Data-driven budget recommendations</h2><p className="text-xs text-slate-400">90-day average + 10% buffer</p></div></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{recommendations.slice(0,6).map(r=><div key={r.category} className="rounded-xl bg-slate-50 p-4"><p className="font-semibold text-slate-800">{r.category}</p><p className="text-xs text-slate-400 mt-1">Average {formatINR(r.average_monthly)}</p><p className="text-lg font-black text-blue-700 mt-2">{formatINR(r.recommended_budget)}</p><p className="text-[11px] text-slate-400">Suggested monthly limit</p></div>)}</div></div>
  <div className="card"><h2 className="font-bold text-slate-800 mb-4">What changed this month?</h2><div className="grid sm:grid-cols-3 gap-4"><div><p className="text-xs text-slate-400">Income</p><p className="text-xl font-black">{formatINR(report?.income||0)}</p><p className="text-xs text-emerald-600">{report?.income_change_pct>=0?"↑":"↓"} {Math.abs(report?.income_change_pct||0).toFixed(1)}% vs last month</p></div><div><p className="text-xs text-slate-400">Expenses</p><p className="text-xl font-black">{formatINR(report?.expenses||0)}</p><p className="text-xs text-amber-600">{report?.expense_change_pct>=0?"↑":"↓"} {Math.abs(report?.expense_change_pct||0).toFixed(1)}% vs last month</p></div><div><p className="text-xs text-slate-400">Savings</p><p className="text-xl font-black">{formatINR(report?.savings||0)}</p><p className="text-xs text-blue-600">{Number(report?.savings_rate||0).toFixed(1)}% savings rate</p></div></div></div>
  <div className="card"><h2 className="font-bold text-slate-800 mb-4">Anomaly review ({anomalies.length})</h2>{anomalies.length===0?<p className="text-sm text-slate-400">No unusual spending detected.</p>:<div className="space-y-3">{anomalies.slice(0,8).map(a=><div key={`${a.transaction_id}-${a.anomaly_type}`} className="rounded-xl bg-amber-50 border border-amber-100 p-4"><div className="flex justify-between"><span className="font-semibold">{a.merchant||"Unknown"}</span><span className="text-xs font-bold uppercase">{a.severity}</span></div><p className="text-sm text-slate-600 mt-1">{a.message}</p></div>)}</div>}<p className="text-xs text-slate-400 mt-4">Anomalies are review flags, not confirmed fraud.</p></div>
 </div>
}
