import { useState } from "react";
import { Link, useSearchParams, useNavigate } from "react-router-dom";
import api from "../lib/api";
import toast from "react-hot-toast";

export default function ResetPassword(){
  const [params]=useSearchParams(); const token=params.get("token")||""; const navigate=useNavigate();
  const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [loading,setLoading]=useState(false);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(password.length<8)return toast.error("Password must be at least 8 characters");if(password!==confirm)return toast.error("Passwords do not match");setLoading(true);try{await api.post("/auth/reset-password",{token,new_password:password});toast.success("Password updated successfully");navigate("/login")}catch(err:any){toast.error(err?.response?.data?.detail||"Reset link is invalid or expired")}finally{setLoading(false)}};
  return <div className="min-h-screen bg-[#060b16] text-white flex items-center justify-center p-6"><div className="w-full max-w-md rounded-[2rem] border border-white/10 bg-[#0d1628] p-8 shadow-2xl shadow-black/40"><Link to="/" className="text-2xl font-black">Fin<span className="text-cyan-300">Wise</span></Link><p className="mt-8 text-xs font-semibold uppercase tracking-[.18em] text-blue-300">Account recovery</p><h1 className="mt-2 text-2xl font-bold">Choose a new password</h1>{!token?<p className="mt-4 text-sm text-rose-400">This reset link is missing a token. <Link className="underline" to="/forgot-password">Request a new one.</Link></p>:<form onSubmit={submit} className="mt-7 space-y-4"><div><label className="auth-label">New password</label><div className="auth-input-wrap"><input className="auth-input" type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/></div></div><div><label className="auth-label">Confirm password</label><div className="auth-input-wrap"><input className="auth-input" type="password" minLength={8} required value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repeat your password"/></div></div><button disabled={loading} className="auth-primary w-full">{loading?"Updating...":"Reset password"}</button></form>}<p className="mt-6 text-center text-sm text-slate-500"><Link className="font-semibold text-blue-300" to="/login">Back to sign in</Link></p></div></div>
}
